version: '3.4'

services:
  flashjaysite:
    image: flashjaysite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6666:6666
