version: '3.4'

services:
  flashjaysite:
    image: flashjaysite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6666:6666
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
